# dockerfile(flask)
# Python 3.12 버전으로 베이스 이미지 지정
FROM python:3.12

# 작업 디렉터리 설정
WORKDIR /app  

# 패키지 설치에 필요한 의존성 파일 복사
COPY requirements.txt .  

# requirements.txt에서 나열된 필요한 의존성 설치
RUN pip install -r requirements.txt  

# 애플리케이션 실행에 필요한 파일 복사
COPY . .  


# Flask 실행
CMD ["python", "app.py"]
